name: formatting

on:
  pull_request:
    branches:
      - master
      - independent-installer

jobs:
  indentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: check indentation
        run: ./ci/check-file-indentation.pl *

